### PR TITLE
Camera cleanup

### PR DESCRIPTION
**Pull request by josmas**
Now the camera is the size of the device and the idea of making it a square is by resizing the top and bottom panels accordingly. I've never done anything like this before and don't know how cameras and matrices work, so there's a lot of magic numbers by trial and error. Would be good if someone that has played with cameras before can review. cc/ @canuckjacq @vladoatanasov

### CODE REVIEW

**Comment by vladoatanasov** [comment]
Hi @josmas, I'm going to play with the code tonight, it will be good to remove the magic numbers, but if we are pressed by time and it works, we can leave it like that :)

**Comment by canuckjacq** [comment]
My little comment: This app will be used for approx 2 weeks. We're not too worried about long term code readability :) If it all works on a variety of devices, it's good! (by all means clean up the magic numbers if it's easy and quick, but let's not let it slow things down).

**Comment by canuckjacq** [comment]
Also guys, Jessy is also working on the camera, so make sure you guys are all communicating :+1: 

Have gone from no one working on the camera to 3!

**Comment by jessyconroy** [comment]
@josmas Everything looks good to me. Might need to check the size of the logo when sharing. Looks to shrink atm

**Comment by vladoatanasov** [comment]
I will do that in a separate pull request

**Comment by vladoatanasov** [comment]
Sorry, forgot to merge :)

**Pull request merged**
